# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_trails_meta <- function(tdbSpec, verbose = FALSE) {
    .Call('RTraildb_read_trails_meta', PACKAGE = 'RTraildb', tdbSpec, verbose)
}

read_trails <- function(tdbSpec, first_trail = 0L, last_trail = 0L, sample = FALSE, fraction = 1.0, start_timestamp = 0L, stop_timestamp = 0L, filter = "", verbose = FALSE) {
    .Call('RTraildb_read_trails', PACKAGE = 'RTraildb', tdbSpec, first_trail, last_trail, sample, fraction, start_timestamp, stop_timestamp, filter, verbose)
}

